fix(eslint-config): fix rule member-ordering via updating dependencies
silverhand-io/configs pull request #18
Opened 2022-02-17 12:15 UTC by IceHe

## Summary

- **fix(eslint-config): fix member-ordering rule via updating eslint-config-xo-typescript dependency to 0.50.0**
- chore(eslint-config): update eslint-config-xo dependency to 0.40.0
- chore: add .idea to .gitignore

Problem:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/10594507/154479778-72f46207-a360-46a8-9ae2-2ea1e73de0c5.png">

<img width="723" alt="image" src="https://user-images.githubusercontent.com/10594507/154479660-99dfebf8-fedb-4fd7-94a6-6d304e727517.png">

Solution:

- Update the dependencies 
    - eslint-config-xo-typescript to the latest version 0.50.0
        - including the patch: "[Improve ordering in @typescript-eslint/member-ordering](https://github.com/xojs/eslint-config-xo-typescript/commit/384e3701e275dd664d74391e63954fc405427d55)" in [v0.45.0](https://github.com/xojs/eslint-config-xo-typescript/commit/384e3701e275dd664d74391e63954fc405427d55)

> Thanks to @demonzoo

References:

* https://github.com/typescript-eslint/typescript-eslint/blob/v5.6.0/packages/eslint-plugin/docs/rules/member-ordering.md
* https://github.com/typescript-eslint/typescript-eslint/blob/v5.6.0/packages/eslint-plugin/docs/rules/adjacent-overload-signatures.md
* https://eslint.org/docs/rules/grouped-accessor-pairs
* [eslint-config-xo-typescript](https://github.com/xojs/eslint-config-xo-typescript)
    * [v0.45.0](https://github.com/xojs/eslint-config-xo-typescript/commit/384e3701e275dd664d74391e63954fc405427d55)
        * [Improve ordering in @typescript-eslint/member-ordering](https://github.com/xojs/eslint-config-xo-typescript/commit/384e3701e275dd664d74391e63954fc405427d55)
* [eslint-config-xo](https://github.com/xojs/eslint-config-xo) 
    * [v0.40.0](https://github.com/xojs/eslint-config-xo/releases/tag/v0.40.0)
* Team [discussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1645501572295619) on Slack.

## Linear Issue Reference

LOG-882

## Testing

No need.

2022-02-17 13:11 UTC, demonzoo approved these changes

2022-02-17 15:12 UTC, gao-sun requested changes
hold until we have a clear conclusion

2022-02-22 06:43 UTC, demonzoo approved these changes
LGTM

2022-02-22 07:26 UTC, gao-sun approved these changes

2022-02-22 07:26 UTC, merged